import { Project } from "@/types/project";

export const projects: Project[] = [
  {
    slug: "allbarber",
    title: "AllBarber",
    shortDescription:
      "A multi-tenant SaaS platform for barbershops combining real-time queue management, point-of-sale with tipping, staff scheduling and client CRM.",
    problemStatement: [
      "Barbershops operate in a mix of appointment-based and walk-in models, making scheduling chaotic. Customers face long, unpredictable wait times, while barbers lack visibility into their day's flow and earnings.",
      "Managing payments is fragmented—cash, card, and tips often require separate systems, leading to accounting headaches and tip distribution disputes among staff.",
      "Owners of multi-location shops need a unified view of performance across sites, but data is siloed and security concerns make it hard to share infrastructure.",
    ],
    solution: [
      "Built a secure multi-tenant platform using Supabase and PostgreSQL with Row-Level Security (RLS) to ensure complete data isolation between barbershops while sharing a single codebase and infrastructure.",
      "Implemented a flexible scheduling engine supporting Walk‑In Only, Hybrid, and Appointment modes. A real‑time queue system allows customers to join remotely via QR code, receive SMS updates with ETA, and reduces wait times by 25% through smart allocation.",
      "Developed an integrated Point‑of‑Sale (POS) system with Stripe Terminal for in‑person payments, cash tracking, and automated tip handling. Supports multiple tip policies (direct, pool, split) with a TipLedger that auto‑adjusts on refunds and simplifies payroll exports.",
      "Created a lightweight CRM to store client notes, preferences, and no‑show scores, enabling personalized service and loyalty features. Basic inventory management tracks products, suppliers, and low‑stock alerts.",
      "Delivered role‑based dashboards (Owner, Manager, Barber, Front Desk) with real‑time analytics on revenue, utilization, tip percentages, and no‑show rates. Daily close reports automate end‑of‑day reconciliation.",
      "Leveraged Supabase's real‑time capabilities to sync queue updates, ticket status, and POS transactions across all devices instantly, ensuring staff and customers always have the latest information.",
    ],
    coverImage: "/projects/allbarber.png",
    galleryImages: ["/projects/allbarber.png"],
    techStack: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "RLS",
      "Auth.js",
      "Stripe",
      "Tailwind CSS",
      "Postmark",
      "Twilio",
      "Inngest",
    ],
    role: "Full Stack Developer",
    timeline: "Aug 2025 - Present",
    liveDemoUrl: "https://allbarber-nine.vercel.app/",
    githubUrl: "https://github.com/MinhTam2773/AllBarber",
    isProtected: true,
  },
  {
    slug: "pathr",
    title: "Pathr",
    shortDescription:
      "An AI-powered education and career pathway platform that helps students navigate complex post-secondary options by integrating real-time program data, transfer agreements, and labor market information across Alberta institutions.",
    problemStatement: [
      "Post-secondary data is constantly evolving - programs open and close admission cycles each semester, some institutions operate on traditional semesters while community colleges have 3-4 week terms with frequent class additions. Students struggle to track these rapid changes.",
      "Transfer pathways are complex and underutilized - students don't know they can ladder from diplomas to baccalaureate degrees or pathway from colleges into universities. These articulation agreements exist but are buried in institutional silos.",
      "Students need personalized guidance that considers their unique situation - whether they're fresh graduates looking to continue their education, or professionals seeking to upskill through micro-credentials and certificate programs.",
      "Institutions lack a unified way to communicate their evolving offerings - program statuses (open, closed, waitlisted), new partnerships between post-secondaries, and changing admission requirements are scattered across different websites and PDFs.",
    ],
    solution: [
      "Built a data ingestion pipeline that processes program information from multiple Alberta post-secondary institutions, capturing semester-by-semester updates, admission cycles, and program status changes (open/closed/waitlisted) as they evolve throughout the academic year.",
      "Integrated transfer agreement data to map out credential laddering opportunities - showing students clear pathways from certificates to diplomas to degrees, including partnerships between institutions that enable seamless transitions.",
      "Developed an AI-powered recommendation engine that considers each student's academic background, career interests, and constraints to suggest personalized education pathways, highlighting transfer opportunities they might otherwise miss.",
      "Created real-time program availability tracking that alerts students when programs open for admission or when new sections are added, particularly important for institutions with frequent 3-4 week enrollment cycles.",
      "Implemented automated data refresh mechanisms that keep program information current without manual intervention, solving the challenge of constantly evolving course offerings across different institutional calendars.",
      'Designed an intuitive interface where students can explore "what-if" scenarios - seeing how completing a diploma at one college could lead to a bachelor\'s degree at a university, with clear timelines and costs at each step.',
    ],
    coverImage: "/projects/pathr/landing.png",
    galleryImages: ["/projects/pathr/landing.png", "/projects/pathr/image.png"],
    techStack: [
      "Next.js",
      "TypeScript",
      "Convex",
      "OpenAI",
      "RAG",
      "PostgreSQL",
      "Tailwind CSS",
      "shadcn/ui",
      "Clerk",
    ],
    role: "Full Stack Developer (AI & Data Integration)",
    timeline: "Feb 2026 - Present",
    liveDemoUrl: "",
    githubUrl: "https://github.com/edwinolaez/apas-pathway-tool",
  },
  {
    slug: "vibemap",
    title: "VibeMap",
    shortDescription:
      "An empathetic mapping experiment that captures how spaces feel—using emoji-based reporting and aggregated heatmaps to reveal community energy patterns.",
    problemStatement: [
      "Traditional maps show where things are, but never how spaces feel. People rely on word-of-mouth or personal experience to find places that match their energy, whether it's a quiet study spot or a vibrant social corner.",
      "Existing reporting tools focus on incidents or problems, which can unfairly label neighborhoods or businesses. This negative framing discourages participation and can stigmatize areas based on isolated events.",
      "Communities and urban planners lack tools to understand the emotional dynamics of public spaces in a way that is ethical, aggregated, and privacy-preserving.",
    ],
    solution: [
      'VibeMap reimagines community mapping through a human-centered lens. Users simply tap a location on the map, select an emoji that represents its "vibe," and optionally add a short note—capturing subjective feelings in an intuitive, low-friction way.',
      "Submissions are aggregated in real time using Firebase Firestore, then rendered as soft, pastel-colored heatmaps and emoji markers. A thresholding algorithm prevents single reports from dominating, ensuring patterns reflect collective sentiment rather than outliers.",
      'The design deliberately avoids harsh colors or judgmental labels—instead using a gentle spectrum from "off-vibe" to "bright"—to frame data as emotional impressions rather than definitive statements. No individual submissions are exposed, preserving user privacy.',
      "Built during a hackathon, the lightweight interface combines Next.js with Leaflet and OpenStreetMap for seamless map interaction, demonstrating how technology can help communities understand shared experiences without amplifying harm.",
    ],
    coverImage: "/projects/vibemap.png",
    galleryImages: [
      "/projects/vibemap.png",
      "/projects/vibemap/image.png",
    ],
    techStack: [
      "Next.js",
      "TypeScript",
      "Firebase Firestore",
      "Leaflet.js",
      "OpenStreetMap",
      "Tailwind CSS",
      "React",
    ],
    role: "Backend Developer",
    timeline: "24 hour hackathon",
    liveDemoUrl: "https://vibemap-app.vercel.app",
    githubUrl: "https://github.com/HanxxFeli/VibeMap",
  },
  {
    slug: "b2b-ecommerce",
    title: "B2B Ecommerce Mobile App",
    shortDescription:
      "A React Native (Expo) mobile application enabling wholesale buyers to browse products, place bulk orders, and track order history with a clean, intuitive interface.",
    problemStatement: [
      "Wholesale distributors needed a mobile-friendly ordering solution for their B2B clients, but existing platforms were either desktop-only or too complex for quick, on-the-go purchases.",
      "Buyers wanted a simple way to reorder frequently purchased items, view product catalogs with real-time pricing, and check order status without logging into a full desktop system.",
      "The goal was to build a lightweight, responsive mobile app that connects to an existing ecommerce backend via APIs, providing a seamless ordering experience for business customers.",
    ],
    solution: [
      "Developed a cross-platform mobile application using React Native and Expo, allowing wholesale clients to place orders directly from their smartphones.",
      "Integrated with the client's existing REST API to fetch product catalogs, pricing, and inventory data, ensuring real-time accuracy without building a new backend.",
      "Implemented features such as bulk order entry, quick reorder from history, secure authentication, and order tracking—all within a streamlined mobile UI.",
      "Designed reusable components and managed state with React hooks and Context API, ensuring smooth navigation and performance.",
      "Delivered a responsive layout that adapts to both phones and tablets, making it easy for buyers to manage their accounts anytime, anywhere.",
    ],
    coverImage: "/projects/ecommerce.png",
    galleryImages: ["/projects/ecommerce.png"],
    techStack: [
      "React Native",
      "Expo",
      "TypeScript",
      "React Navigation",
      "Context API",
      "REST API Integration",
      "Axios",
      "AsyncStorage",
    ],
    role: "Frontend Mobile Developer",
    timeline: "Dec 2025",
    liveDemoUrl: "",
    githubUrl: "https://github.com/MinhTam2773/B2B-Ecommerce",
  },
  {
    slug: "sharie",
    title: "Sharie",
    shortDescription:
      "A social audio sharing platform where users can upload, discover, and discuss audio content in real-time, combining elements of SoundCloud and modern messaging apps.",
    problemStatement: [
      "Audio content creators lacked a dedicated space to share their work and engage with listeners beyond static comments. Existing platforms separated content discovery from community interaction.",
      "Listeners wanted to discuss tracks, ask questions, and connect with others in real-time while listening, but traditional music platforms offered only delayed, thread-based comments.",
      "The challenge was to build a cohesive experience where audio playback and social interaction happen simultaneously, with real-time chat and notifications.",
    ],
    solution: [
      "Developed a full-stack MERN application (MongoDB, Express, React, Node.js) with a custom authentication system using JWT and Axios for secure API communication.",
      "Implemented real-time chat functionality using WebSockets, allowing users to send direct messages, participate in group conversations, and react to messages while listening to audio.",
      "Built audio upload and streaming capabilities with support for MP3/WAV files, including waveform visualization using Wavesurfer.js and a custom audio player with play/pause, seek, and volume controls.",
      "Created social features such as liking, commenting, reposting, saving audio to personal libraries, and following other users – all with real-time updates via WebSocket events.",
      "Designed an intuitive UI with React and Tailwind CSS, featuring infinite scroll feeds, category-based browsing, and user profiles with stats (uploads, followers, following).",
      "Engineered the backend with Express and MongoDB, including robust data models for users, audio posts, playlists, messages, and notifications. Used middleware for authentication and error handling.",
    ],
    coverImage: "/projects/sharie.png",
    galleryImages: ["/projects/sharie.png"],
    techStack: [
      "MongoDB",
      "Express.js",
      "React",
      "Node.js",
      "WebSockets",
      "JWT",
      "Axios",
      "Tailwind CSS",
      "Wavesurfer.js",
      "React Router",
      "Context API",
    ],
    role: "Full Stack Developer",
    timeline: "June 2025",
    liveDemoUrl: "",
    githubUrl: "https://github.com/MinhTam2773/Sharie",
  },
];
